<?xml version="1.0" standalone="yes"?>
<!DOCTYPE studentList [
    <!ELEMENT studentList (student*)>
    <!ELEMENT student (firstName,lastName,results)>
    <!ATTLIST student studentID CDATA #REQUIRED>
    <!ELEMENT firstName (#PCDATA)>
    <!ELEMENT lastName (#PCDATA)>
    <!ELEMENT results (subject*)>
    <!ELEMENT subject (code, creditPoint, mark, grade)>
    <!ELEMENT code (#PCDATA)>
    <!ELEMENT creditPoint (#PCDATA)>
    <!ELEMENT mark (#PCDATA)>
    <!ELEMENT grade (#PCDATA)>
]>
<studentList>
    <student studentID="1231234">
        <firstName>John</firstName>
        <lastName>Smith</lastName>
        <results>
            <subject>
                <code>MATH101</code>
                <creditPoint>4</creditPoint>
                <mark>85</mark>
                <grade>A</grade>
            </subject>
            <subject>
                <code>ECON101</code>
                <creditPoint>5</creditPoint>
                <mark>70</mark>
                <grade>B</grade>
            </subject>
            <subject>
                <code>CS100</code>
                <creditPoint>5</creditPoint>
                <mark>80</mark>
                <grade>A</grade>
            </subject>
            <subject>
                <code>LAW121</code>
                <creditPoint>6</creditPoint>
                <mark>75</mark>
                <grade>B</grade>
            </subject>
        </results>
    </student>
</studentList>